### PR TITLE
SG-34297 - Rebranding

### PR DESCRIPTION
**Pull request by juanburgosautoglb**
Change all the shotgrid/shotgun occurrences in the repository.

### CODE REVIEW

**Review by NorberMV — CHANGES_REQUESTED** [review]
HI @juanburgosautoglb, looks good in general. But for the icon changes you made in `cep/images` you will need to build and sign  a new CEP extension with a new version otherwise changes are not showing up in the ui.

**Comment by julien-lang** [comment]
> HI @juanburgosautoglb, looks good in general. But for the icon changes you made in `cep/images` you will need to build and sign a new CEP extension with a new version otherwise changes are not showing up in the ui.

Done! We can now review and test.

**Review by NorberMV — APPROVED** [review]
LGTM! Thanks

**Review by julien-lang — APPROVED** [review]
LGTM!

**Review by julien-lang — APPROVED** [review]

**Pull request merged**
