### PR TITLE
SG-7336 Hard to see SG project name in Photoshop/After Effects: missing contrast between text and background

### PR DESCRIPTION
**Pull request by julien-lang**
The project link (after being clicked once) is displayed in a color that is not contrasted enough with the background

image

### CODE REVIEW

**Comment by julien-lang** [comment]
Please check my last commit. I am not so sure if we want to differentiate the sg_value_link from other links.
I could not find other links to compare it with. Basically, regular links would be "blue" and sg_value_link would be white.

I think blue is better since the hover is white.

**Review by NorberMV — COMMENTED** [review]
LGTM !, not sure if maybe this change will require to bump the version and repackage before merge.

**Comment by julien-lang** [comment]
> !, not sure if maybe this change will require to bump the version and repackage before merge.

This is a good point @NorberMV! I am going to investigate about that.

**Comment by julien-lang** [comment]
> > not sure if maybe this change will require to bump the version and repackage before merge.
> 
> This is a good point @NorberMV! I am going to investigate about that.

Done, check the last commit.

**Review by NorberMV — APPROVED** [review]
LGTM !, maybe should we update something in the README.md about the process of recompile the plugin, I just found this [PR](https://github.com/shotgunsoftware/tk-framework-adobe/pull/18) explaining the process a little better.

**Comment by NorberMV** [comment]
Seems like you´ll need to run the linter, the code validation is failing on Azure.

**Review by NorberMV — CHANGES_REQUESTED** [review]
Seems like you´ll need to run the linter, the code validation is failing on Azure.

**Comment by julien-lang** [comment]
> Seems like you´ll need to run the linter, the code validation is failing on Azure.

Fixed!

**Review by NorberMV — APPROVED** [review]
LGTM!

**Pull request merged**
